### ISSUE TITLE
Version 3.3.1 breaking change.

### ISSUE THREAD

**Issue by MicahRus** [jamesmbourne/aws4-axios#1279]
Version 3.3.1 breaks with our usage of your library.  Reverting back to version 3.3.0 works.

Error: 
```
error TypeError: axios_1.AxiosHeaders is not a constructor
    at /home/micah/Documents/repo/ubiIotProvisionService/node_modules/.pnpm/aws4-axios@3.3.1_@aws-sdk+credential-provider-node@3.515.0_axios@0.27.2/node_modules/aws4-axios/dist/interceptor.js:96:25
    at Generator.next (<anonymous>)
    at /home/micah/Documents/repo/ubiIotProvisionService/node_modules/.pnpm/aws4-axios@3.3.1_@aws-sdk+credential-provider-node@3.515.0_axios@0.27.2/node_modules/aws4-axios/dist/interceptor.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/home/micah/Documents/repo/ubiIotProvisionService/node_modules/.pnpm/aws4-axios@3.3.1_@aws-sdk+credential-provider-node@3.515.0_axios@0.27.2/node_modules/aws4-axios/dist/interceptor.js:27:12)
    at /home/micah/Documents/repo/ubiIotProvisionService/node_modules/.pnpm/aws4-axios@3.3.1_@aws-sdk+credential-provider-node@3.515.0_axios@0.27.2/node_modules/aws4-axios/dist/interceptor.js:89:24
```

Implementation:
```
  const instance = axios.create(
    {
      baseURL: uri,
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
      },
      timeout,
    },
  )

  const interceptorOptions = {region: 'ap-southeast-2', service: 'execute-api'}
  const interceptor = aws4Interceptor({options: interceptorOptions})

  instance.interceptors.request.use(interceptor)
```

**Comment by jamesmbourne** [comment]
Hey @MicahRus, you are running a pretty old version of `axios` - [the requirement](https://github.com/jamesmbourne/aws4-axios/blob/main/package.json#L66-L68) is now `>=1.6.0`. Could you try upgrading and see if you still face this problem?
